use_frameworks!

platform :ios, '10.0'

target 'CredentialValidator_Example' do
  pod 'CredentialValidator', :path => '../'

  target 'CredentialValidator_Tests' do
    inherit! :search_paths

    
  end
end
